micronaut:
  application:
    name: ConquerorPCs

  server:
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - "http://127.0.0.1:5500"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
